

Need to start with

python -m http.server 8888 &

for non-server situation.

* links

[[~/geek/javascript.org]]  (tips and tech on d3js)

[[~/energy/fias-private.org]] (comparison with other websites)

* TODO

** DONE export generation data and flows

** Represent directional flows

Either with animation OR with arrow

** DONE Represent generation at each node

https://bl.ocks.org/mbostock/3887235

Pie chart - how to represent load??? red circle under (if gen > load); red circle over (if gen < load)

What to do with storage

have pie for BOTH load and generation, storage flipping between the two

** DONE make load transparent?

flipping z-order not supported in SVG, only in CSS

SVG paints in order of SVG

** Legend for generation, storage, load

** Benefits paper first

~/results/supplementary_data_benefits_of_cooperation/results$

https://zenodo.org/record/804338

** Allow different scenarios to be loaded

This will require more work...

** Play button

https://bl.ocks.org/officeofjane/47d2b0bfeecfcb41d2212d06d095c763

** DONE Area not radius proportional to power

** DONE Zoom, bring down Scandinavia

** Parallel graph

Either for whole of Europe or individual country - drop-down menu to choose

** see per-country time series, total capacity and energy

also per scenario settings

e.g. user from Ireland can see how each country deals with down periods with and without transmission


** tmrow style wind/solar animation?


why doesn't Chrome crash with tmrow.co wind animation??? If not, should be able to deal with network flows


** Text

Copyright Natural Earth

Link to paper, zenodo

Link to pypsa home

AGPL

Link to github PyPSA_animation?

** Make export_network into a library

** Use selection of snapshots rather than num_snapshots

** Shrink Natural Earth file?
